Feature/result pagination
joshsoftware/FACET_BackEnd pull request #12
Opened 2022-10-17 09:04 UTC by poojan-2601

2022-10-17 16:16 UTC, tanmaythole requested changes
Hello @poojan-2601, I have reviewed PR and suggested some changes, check it out and let me know if you have any questions.
Keep in mind, add space after ',' wherever needed.

2022-10-17 16:16 UTC, tanmaythole commented on app/models/ResultModel.py
> +    def get_paginated_results(project_id,page_no,row_size):
After ',' add space e.g. project_id, page_no

2022-10-17 16:16 UTC, tanmaythole commented on app/routes/results.py
> +        row_size = request.args.get("pageSize") or None
I think, In row_size, instead of None directly add default size i.e. 20, so in ResultModel.py code may be reduced (line no. 62 to 68).

```suggestion
        row_size = request.args.get("pageSize") or 20
```

2022-10-17 16:16 UTC, tanmaythole commented on app/helpers/utils.py
> +    if project is not None:
I think in if condition "project is not None" and only "project" both have same meaning, so "is not None" maybe useless. Check whether its required or not.

2022-10-17 16:16 UTC, tanmaythole commented on app/helpers/utils.py
> +    if project is not None:
```suggestion
    if project:
```

2022-10-17 16:16 UTC, tanmaythole commented on app/helpers/utils.py
> +        return ProjectModel.is_a_member_of_project(project_id,user_id)
I think if the condition is true function returns, then we can reduce if-else ladder by avoiding else.
```suggestion
    if project_id is None or user_id is None:
        return False
    return ProjectModel.is_a_member_of_project(project_id,user_id)
```

2022-10-17 16:16 UTC, tanmaythole commented on app/models/ResultModel.py
> +            data = ResultModel.query.filter_by(project=project_id).paginate(page=int(page_no),per_page=int(row_size))
add space after ','
```suggestion
            data = ResultModel.query.filter_by(project=project_id).paginate(page=int(page_no), per_page=int(row_size))
```

2022-10-17 16:16 UTC, tanmaythole commented on app/routes/results.py
> +            if page_no is not None:
```suggestion
            if page_no:
```

2022-10-17 16:16 UTC, tanmaythole commented on app/routes/results.py
> +                return jsonify({"results": data}), 200
I think totalResults should be included to the response

2022-10-17 17:53 UTC, poojan-2601 commented
Hi @tanmaythole , 
I have taken your suggestions into account, and have made changes to the code accordingly. I have added better error handling for out-of-bounds result queries and included the total_results dictionary you requested.

2022-10-18 02:02 UTC, tanmaythole requested changes

2022-10-18 02:02 UTC, tanmaythole commented on app/models/ResultModel.py
> +            return data
I think directly returning data, total_results is suitable instead of appending total_results into data

```suggestion
            total_results = ResultModel.query.filter_by(project=project_id).count()
            return data, total_results
```

2022-10-18 02:02 UTC, tanmaythole commented on app/routes/results.py
> +            data = ResultModel.get_paginated_results(project_id=project, page_no=page_no, row_size=row_size)
directly get data & total_results instead of pop

2022-10-18 05:43 UTC, tanmaythole approved these changes

2022-10-18 05:43 UTC, merged