Feature/testsuite
joshsoftware/FACET_BackEnd pull request #18
Opened 2022-11-04 05:45 UTC by poojan-2601

2022-11-06 14:47 UTC, tanmaythole requested changes
Some suggestions for all files:
- instead of the 'Error' key in the response make it 'error'
- instead of the 'Success' key in the response make it 'message'
- in the try-except block, pass the error message in the 'error' key

2022-11-06 14:47 UTC, tanmaythole commented on app/models/__init__.py
> +from .TestsuiteModel import TestsuiteModel,TestsuiteSchema
Format document
```suggestion
from .TestsuiteModel import TestsuiteModel, TestsuiteSchema
```

2022-11-06 14:47 UTC, tanmaythole commented on app/models/TestsuiteModel.py
> +from marshmallow import Schema,fields
make sure you formatted document

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/teststeps.py
> +            teststep.name = name
I think instead of writing multiple lines only for condition check and update it, we can directly check and store in one linear code 
e.g.
```suggestion
        teststep.name = req_data.get('name') if req_data.get('name') else teststep.name
```

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/teststeps.py
> +            teststep.payload_id = payload
same for this also, one linear code

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/teststeps.py
> +            teststep.name = name
check this we can do it or not

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/teststeps.py
> +    return jsonify({"Success": "Teststep Updated successfully"}), 200
success to message

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/teststeps.py
> +        return jsonify({"success": "Teststep created successfully!"}), 201
success to message

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testdata.py
> +            testdata.expected_outcome = expected_outcome
can we implement this multiple lines of 'if' statement to one line, for more check comments in teststeps.py file

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testdata.py
> +    return jsonify({"message" : "Testdata deleted successfully"}),200
This should be written in the above try block, if anything fails server may crash and gives an error with the 500 code. So I think this code should be written inside the above try-except block

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +        return jsonify({"Error": "You do not have access to this project, kindly connect to project admin to make updates in the project components"}), 401
Error -> error

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +        return jsonify(str(err)), 400
```suggestion
        return jsonify({"error": str(err)}), 400
```

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +        testcase.execution_sequence = testcase.execution_sequence + \
what does '\\' means here?

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +    return jsonify({"success": "testcase created with the given teststeps"}), 200
success -> message

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +        return jsonify(str(e)), 400
str(e) should be wrap in error key, e.g. {"error": str(e)}

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +            testcase.environment = environment
convert into one linear if

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/testcases.py
> +        return jsonify(str(err)), 400
Change success -> message and Error -> error  in all places wherever necessary

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/scheduler.py
>              return jsonify({"Error" : "You do not have access to this project, kindly connect to project admin to get access to scheduled jobs of the project"}),401
Error -> error, also check in other places
Success -> message,
jsonify(str(err)) -> jsonify({"error": str(err)})

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/headers.py
> +        return jsonify(err), 400
jsonify(err) -> jsonify({"error": err})

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/environments.py
> +    return jsonify({"message": "Environment deleted successfully"}), 200
move this inside to the above try block

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/environments.py
> +        return jsonify(str(err)), 400
error key missing in the response

2022-11-06 14:47 UTC, tanmaythole commented on app/routes/endpoints.py
> +        return jsonify(str(err))
error key missing in response

2022-11-08 10:30 UTC, poojan-2601 commented on app/routes/teststeps.py
> +            teststep.name = name
Hi Tanmay, I have made the changes as above after testing for files where the update does not require any for-loop or complex if-else operation, however in files where such complexity exists, I have not changed them in order to maintain uniformity.

2022-11-08 11:17 UTC, poojan-2601 commented on app/routes/teststeps.py
> +            teststep.name = name
Hi tanmay, ignore the above comment, I have implemented your suggestion.

2022-11-21 12:01 UTC, tanmaythole approved these changes

2022-11-21 14:19 UTC, merged